import { ACCEPTED_FILE_TYPES } from "constants/application"

// This will change once we know what we are displaying
// In future milestone will change to a type generated by the backend
export type UploadProp = {
  name: string,
  type: (typeof ACCEPTED_FILE_TYPES)[number],
  src: string
  thumbnailSrc?: string
}

export type Uploads = {
  [asset_id: string]: UploadProp
}