import { ACCEPTED_FILE_TYPES } from "constants/application";

// This will change once we know what we are displaying
// In future milestone will change to a type generated by the backend
export type UploadProp = {
  name: string;
  type: (typeof ACCEPTED_FILE_TYPES)[number];
  src: string;
  thumbnailSrc?: string;
};

export type Uploads = {
  [assetId: string]: UploadProp;
};

export type VisualSize = {
  height: number;
  width: number;
};

export type VisualPosition = {
  x: number;
  y: number;
};

export type Visual = {
  assetId: string;
  uploadData: UploadProp;
  position: VisualPosition;
  size: VisualSize;
  isHovered?: boolean;
  // set to true when visual need to be set to original size, false otherwise
  useOriginalSizeOnLoad: boolean;
};
