import { ACCEPTED_FILE_TYPES, ACTIONS, GESTURES } from "constants/application";

// This will change once we know what we are displaying
// In future milestone will change to a type generated by the backend
export type UploadProp = {
  name: string;
  type: (typeof ACCEPTED_FILE_TYPES)[number];
  src: string;
  thumbnailSrc?: string;
};

export type Uploads = {
  [assetId: string]: UploadProp;
};

export type VisualSize = {
  height: number;
  width: number;
};

export type VisualPosition = {
  x: number;
  y: number;
};

export type Visual = {
  assetId: string;
  uploadData: UploadProp;
  position: VisualPosition;
  size: VisualSize;
  isHovered?: boolean;
  // set to true when visual need to be set to original size, false otherwise
  useOriginalSizeOnLoad: boolean;
};

export type ActionType = (typeof ACTIONS)[number];

export type InteractionInput = {
  type: ActionType;
  position: VisualPosition;
  targetId?: string;
  isHovered?: boolean;
};

export type GestureType = (typeof GESTURES)[number];

export type ActionPayload = {
  action: ActionType;
  coordinates: VisualPosition[];
  resizeScale?: number;
};
