name: "build development"
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          # TODO: Add test
          runCmd: cd hansroslinger && npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: main-devel
    if: github.repository == 'Monash-FIT3170/2025W2-HansRoslinger'
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull ./hansroslinger --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy ./hansroslinger --prod --token=${{ secrets.VERCEL_TOKEN }}
