name: "build development"
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          # TODO: Add test
          runCmd: cd hansroslinger && npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: develop
    if: github.repository == 'Monash-FIT3170/2025W2-HansRoslinger'
    defaults:
      run:
        shell: bash
        working-directory: hansroslinger
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
