name: "Deploy main"
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  pull-requests: write # Add PR comments

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          # TODO: Add test
          runCmd: cd hansroslinger && npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: main-devel
    if: github.repository == 'Monash-FIT3170/2025W2-HansRoslinger'
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
