name: "Deploy develop"
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
permissions:
  pull-requests: write # Add PR comments

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
        
      - name: Install apt
        run: |
          sudo apt install -y npm
      - name: Lint
        run: |
          cd hansroslinger && npm install && npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: develop
    if: github.repository == 'Monash-FIT3170/2025W2-HansRoslinger'
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
