name: "Deploy develop"
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd hansroslinger && npm install

      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          eslint_dir: hansroslinger/
          prettier_dir: hansroslinger/
          eslint: true
          prettier: true
          auto_fix: false
          continue_on_error: true

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: develop
    if: github.repository == 'Monash-FIT3170/2025W2-HansRoslinger'
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --project='hans-roslinger'

      - name: Build on CI
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy and Capture Preview URL
        id: deploy
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tee vercel-deploy.log
          echo "url=$(tail -n 1 vercel-deploy.log)" >> $GITHUB_OUTPUT

      - name: Comment PR with Preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = '${{ steps.deploy.outputs.url }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment ready: ${url}`
            })
